[package]
name = "hyperion-crafting"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
valence_protocol.workspace = true
serde_json = "1.0.128"
anyhow = "1.0.89"
flecs_ecs.workspace = true
heapless = "0.8.0"
slotmap = "1.0.7"

[lints]
workspace = true
