# https://nnethercote.github.io/perf-book/compile-times.html
# https://nnethercote.github.io/perf-book/build-configuration.html#minimizing-compile-times

# Define an argument for the Rust nightly version
ARG RUST_NIGHTLY_VERSION=nightly-2024-04-10

# Use Debian bookworm
FROM debian:bookworm-slim as packages

# Update and install required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    llvm \
    lld \
    mold \
    cmake \
    git \
    ca-certificates  # Adding ca-certificates here

# Ensure certificates are updated
RUN update-ca-certificates

FROM packages as builder

# Install Rust Nightly


ARG RUST_NIGHTLY_VERSION
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
   $HOME/.cargo/bin/rustup default ${RUST_NIGHTLY_VERSION}

ENV CARGO_HOME=/root/.cargo

ENV PATH="/root/.cargo/bin:${PATH}"

CMD ["/bin/bash"]
