# Define an argument for the Rust nightly version
ARG RUST_NIGHTLY_VERSION=nightly-2024-03-16

# Use Debian as base image
FROM debian:bullseye-slim as packages

# Install curl, build-essential (Debian's equivalent of build-base), and OpenSSL development packages
RUN apt-get update && \
    apt-get install -y curl build-essential pkg-config libssl-dev

FROM packages as builder

# Install Rust Nightly
ARG RUST_NIGHTLY_VERSION
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
   $HOME/.cargo/bin/rustup default ${RUST_NIGHTLY_VERSION}

ENV PATH="/root/.cargo/bin:${PATH}"

# Set the working directory
WORKDIR /app

# Copy the Cargo configuration and source code
COPY Cargo.toml Cargo.lock ./

COPY prototype/Cargo.toml ./prototype/Cargo.toml
COPY prototype/src ./prototype/src

COPY server/Cargo.toml ./server/Cargo.toml
COPY server/src ./server/src

# Build the source code using Rust Nightly
# Note: The --mount option requires BuildKit. Ensure it's enabled in your Docker setup.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --release --locked -p server

# Copy the built executable from the cache to a clean directory
RUN --mount=type=cache,target=/app/target \
    mkdir -p /build && \
    cp target/release/server /build/server

# Using Debian slim image for the final stage to minimize the size
FROM debian:bullseye-slim

# Install OpenSSL, required at runtime for many applications
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*

# Copy the built executable into the final image
COPY --from=builder /build/server /

EXPOSE 25565
ENTRYPOINT ["/server"]
