[package]
name = "hyperion-gui"
version.workspace = true
edition.workspace = true

[dependencies]
flecs_ecs = { workspace = true }
hyperion = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
valence_protocol = { workspace = true }

[lints]
workspace = true
