[package]
name = "hyperion-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
flecs_ecs = { workspace = true }
hyperion = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
valence_protocol = { workspace = true }

[lints]
workspace = true
