[package]
name = "packet-inspector"
description = "A simple Minecraft proxy for inspecting packets."
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
valence_protocol = { workspace = true, features = ["compression"] }
anyhow.workspace = true
bytes.workspace = true
flate2.workspace = true
flume.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
time = { workspace = true, features = ["local-offset"] }
egui.workspace = true
eframe = { workspace = true, features = [
    "persistence",
    "wgpu",
] }
egui_dock = { workspace = true, features = ["serde"] }
itertools.workspace = true
syntect = { workspace = true, default-features = false, features = [
    "default-fancy",
] }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
anyhow.workspace = true
syn = { workspace = true, features = ["full"] }
valence_build_utils.workspace = true
quote = { workspace = true, features = ["proc-macro"] }
serde_json = { workspace = true, features = ["raw_value"] }
proc-macro2.workspace = true
serde = { workspace = true, features = ["derive"] }
