[package]
name = "rayon-local"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[features]
evenio = ["dep:evenio"]
default = ["evenio"]

[dependencies]
evenio = { workspace = true , optional = true }
rayon = "1.10.0"

[dev-dependencies]
divan = "0.1.14"

[lints.rust]
#missing_docs= "warn"

[lints.clippy]
complexity = "deny"


nursery = { level = "deny", priority = -1 }
redundant_pub_crate = "allow"

pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"
