[target.x86_64-apple-darwin]
rustflags = [
    "-Ctarget-cpu=native",
    "-C",
    "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
    "-Zthreads=0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
    "-Zthreads=0",
]

[registries.crates-io]
protocol = "sparse"
