[package]
name = "system-order"
version.workspace = true
edition.workspace = true
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
derive_more.workspace = true
flecs_ecs.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
