[dependencies]

[lints]
workspace = true

[package]
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
edition = "2024"
name = "hyperion-minecraft-proto"
publish = false
readme = "README.md"
version = "0.1.0"
