[package]
name = "spatial"
version.workspace = true
edition.workspace = true
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
bvh-region.workspace = true
flecs_ecs.workspace = true
geometry.workspace = true
hyperion.workspace = true
ordered-float.workspace = true
rayon.workspace = true

[lints]
workspace = true
