[package]
name = "bvh"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
bitfield-struct = "0.6.0"
bumpalo-herd = "0.1.2"
glam = "0.27.0"
nonmax = "0.5.5"
parking_lot = "0.12.1"
rayon = "1.10.0"
sharded-slab = "0.1.7"
slab = "0.4.9"
smallvec.workspace = true

[dev-dependencies]
divan = "0.1.14"
rand = "0.8.5"
ordered-float = "4.2.0"
fastrand = "2.0.2"

[[bench]]
name = "sort"
harness = false

[[bench]]
name = "bvh"
harness = false

[lints.clippy]
complexity = "deny"


nursery = { level = "deny", priority = -1 }
redundant_pub_crate = "allow"

#pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"
