name: Bench

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  RUST_NIGHTLY_TOOLCHAIN: nightly-2024-03-24
  RUSTFLAGS: -Clinker=/usr/bin/clang -Clink-arg=--ld-path=/usr/bin/mold -Ctarget-cpu=native -Zshare-generics=y -Zthreads=0 -Zexport-executable-symbols

jobs:
  export:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1

      - name: Install cargo-export
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-export

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo export
        run: cargo export target/benchmarks -- bench --bench=side_by_side

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bench_side_by_side
          path: target/benchmarks/side_by_side

  compare:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # download artifact from previous job
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          commit: ${{ github.event.pull_request.base.sha }}
          name: bench_side_by_side-${{ github.event.pull_request.base.sha }}
          path: /tmp/bench/

      - name: get tree of /tmp/bench
        run: tree /tmp/bench

      - name: run nm
        run: nm /tmp/bench/side_by_side

      - uses: rui314/setup-mold@v1

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}

      - uses: Swatinem/rust-cache@v2


      - name: Run cargo bench
        run: cargo bench --bench=side_by_side -- compare /tmp/bench/side_by_side

      - name: remove /tmp/bench
        run: rm -rf /tmp/bench
