name: Bench

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  RUST_NIGHTLY_TOOLCHAIN: nightly-2024-03-24
  RUSTFLAGS: -Clinker=/usr/bin/clang -Clink-arg=--ld-path=/usr/local/bin/mold -Ctarget-cpu=native -Zshare-generics=y -Zthreads=0 -Zexport-executable-symbols

jobs:
  export:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1

      - name: Install cargo-export
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-export

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo export
        run: cargo export target/benchmarks -- bench --bench=side_by_side

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bench_side_by_side
          path: target/benchmarks/side_by_side

  compare:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # download artifact from previous job
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          commit: ${{ github.event.pull_request.base.sha }}
          name: bench_side_by_side
          path: /tmp/bench/

      - uses: rui314/setup-mold@v1

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}

      - uses: Swatinem/rust-cache@v2


      - name: Run cargo bench
        run: cargo bench --bench=side_by_side -- compare /tmp/bench/side_by_side > bench_output.txt

      - name: remove /tmp/bench
        run: rm -rf /tmp/bench


      - name: Post benchmark results as PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'bench_output.txt';
            const output = fs.readFileSync(path, 'utf8');
            const originalSha = context.payload.pull_request.base.sha;
            
            const issue_number = context.issue.number;
            if(issue_number) {
              const comment = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: `### Benchmark Results\n\`\`\`\n${output}\`\`\`\n\nComparing to ${originalSha}`,
              };
              await github.rest.issues.createComment(comment);
            } else {
              console.log('This action must be run in the context of a pull request');
            }
