name: Export benchmarks

on:
  push:
    branches: [ main ]

env:
  RUST_NIGHTLY_TOOLCHAIN: nightly-2024-03-24
  RUSTFLAGS: -C target-cpu=native -Zexport-executable-symbols -Zshare-generics=y -Zthreads=0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-export
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-export

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo export
        run: cargo export target/benchmarks -- bench --bench=side_by_side

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bench_side_by_side
          path: target/benchmarks/side_by_side-${{ github.sha }}
