name: Publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push hyperion-proxy
        uses: depot/build-push-action@v1
        with:
          project: qln0fqqvvd
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          target: hyperion-proxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hyperion-proxy:latest
            ghcr.io/${{ github.repository }}/hyperion-proxy:${{ github.sha }}
      - name: Build and push tag
        uses: depot/build-push-action@v1
        with:
          project: qln0fqqvvd
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          target: tag
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/tag:latest
            ghcr.io/${{ github.repository }}/tag:${{ github.sha }}
      - name: Update test server
        env:
          KEY: ${{ secrets.TEST_SERVER_KEY }}
        run: curl -X POST -H "Key: $KEY" https://hyperion-test.duckdns.org
