[package]
name = "hyperion-inventory"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
valence_protocol.workspace = true
flecs_ecs.workspace = true
snafu.workspace = true

[lints]
workspace = true